package hooks

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/saireddy-shyamakura/springx/internal/postgen"
	"github.com/saireddy-shyamakura/springx/internal/prompt"
)

func init() {
	postgen.Register(&composeHook{})
}

type composeHook struct{}

func (c *composeHook) Name() string { return "compose" }

func (c *composeHook) Run(projectPath string, cfg *prompt.ProjectConfig) error {
	hasPostgres := hasDep(cfg.Dependencies, "postgresql", "postgres", "data-jpa")
	hasRedis := hasDep(cfg.Dependencies, "redis", "data-redis")

	// Only generate a compose file when there is at least one infrastructure
	// dependency that benefits from a local container.
	if !hasPostgres && !hasRedis {
		return nil
	}

	content := buildCompose(cfg, hasPostgres, hasRedis)
	dest := filepath.Join(projectPath, "docker-compose.yml")
	return os.WriteFile(dest, []byte(content), 0644)
}

// hasDep returns true if any of the given keywords appear in the dependency list.
func hasDep(deps []string, keywords ...string) bool {
	for _, d := range deps {
		dl := strings.ToLower(d)
		for _, kw := range keywords {
			if strings.Contains(dl, kw) {
				return true
			}
		}
	}
	return false
}

func buildCompose(cfg *prompt.ProjectConfig, postgres, redis bool) string {
	var sb strings.Builder

	sb.WriteString("# docker-compose.yml — local development infrastructure\n")
	sb.WriteString("# Generated by springx. Adjust credentials before use.\n\n")
	sb.WriteString("services:\n\n")

	sb.WriteString("  app:\n")
	sb.WriteString("    build: .\n")
	sb.WriteString("    ports:\n")
	sb.WriteString("      - \"8080:8080\"\n")
	sb.WriteString("    environment:\n")
	sb.WriteString("      SPRING_PROFILES_ACTIVE: dev\n")
	if postgres {
		sb.WriteString("      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb\n")
		sb.WriteString("      SPRING_DATASOURCE_USERNAME: appuser\n")
		sb.WriteString("      SPRING_DATASOURCE_PASSWORD: secret\n")
	}
	if redis {
		sb.WriteString("      SPRING_DATA_REDIS_HOST: redis\n")
		sb.WriteString("      SPRING_DATA_REDIS_PORT: \"6379\"\n")
	}
	sb.WriteString("    depends_on:\n")
	if postgres {
		sb.WriteString("      db:\n")
		sb.WriteString("        condition: service_healthy\n")
	}
	if redis {
		sb.WriteString("      redis:\n")
		sb.WriteString("        condition: service_healthy\n")
	}
	sb.WriteString("    restart: on-failure\n\n")

	if postgres {
		sb.WriteString("  db:\n")
		sb.WriteString("    image: postgres:16-alpine\n")
		sb.WriteString("    environment:\n")
		sb.WriteString("      POSTGRES_DB: appdb\n")
		sb.WriteString("      POSTGRES_USER: appuser\n")
		sb.WriteString("      POSTGRES_PASSWORD: secret\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"5432:5432\"\n")
		sb.WriteString("    volumes:\n")
		sb.WriteString("      - postgres_data:/var/lib/postgresql/data\n")
		sb.WriteString("    healthcheck:\n")
		sb.WriteString("      test: [\"CMD-SHELL\", \"pg_isready -U appuser -d appdb\"]\n")
		sb.WriteString("      interval: 5s\n")
		sb.WriteString("      timeout: 5s\n")
		sb.WriteString("      retries: 5\n\n")
	}

	if redis {
		sb.WriteString("  redis:\n")
		sb.WriteString("    image: redis:7-alpine\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"6379:6379\"\n")
		sb.WriteString("    healthcheck:\n")
		sb.WriteString("      test: [\"CMD\", \"redis-cli\", \"ping\"]\n")
		sb.WriteString("      interval: 5s\n")
		sb.WriteString("      timeout: 3s\n")
		sb.WriteString("      retries: 5\n\n")
	}

	sb.WriteString("volumes:\n")
	if postgres {
		sb.WriteString("  postgres_data:\n")
	}
	if redis {
		sb.WriteString("  redis_data:\n")
	}

	return sb.String()
}
