package hooks

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/saireddy-shyamakura/springx/internal/postgen"
	"github.com/saireddy-shyamakura/springx/internal/prompt"
)

func init() {
	postgen.Register(&gitHook{})
}

type gitHook struct{}

func (g *gitHook) Name() string { return "git" }

func (g *gitHook) Run(projectPath string, cfg *prompt.ProjectConfig) error {
	// Bail out early if git is not available on this machine.
	if _, err := exec.LookPath("git"); err != nil {
		return fmt.Errorf("git not found in PATH: %w", err)
	}

	// Skip if the directory is already a git repository.
	if _, err := os.Stat(filepath.Join(projectPath, ".git")); err == nil {
		return nil
	}

	if err := runGit(projectPath, "init"); err != nil {
		return fmt.Errorf("git init failed: %w", err)
	}

	// Configure a throwaway identity if none is set — prevents commit errors in
	// CI environments where no global git config exists.
	if !hasGitConfig("user.email") {
		_ = runGit(projectPath, "config", "user.email", "springx@local")
		_ = runGit(projectPath, "config", "user.name", "springx")
	}

	if err := runGit(projectPath, "add", "-A"); err != nil {
		return fmt.Errorf("git add failed: %w", err)
	}

	msg := fmt.Sprintf(
		"chore: initial project scaffold\n\nGenerated by springx on %s\nProject: %s",
		time.Now().UTC().Format("2006-01-02"),
		cfg.ProjectName,
	)
	if err := runGit(projectPath, "commit", "-m", msg); err != nil {
		return fmt.Errorf("git commit failed: %w", err)
	}

	return nil
}

// runGit executes a git subcommand in dir, returning combined output on failure.
func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w\n%s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// hasGitConfig returns true if the global git config contains a value for key.
func hasGitConfig(key string) bool {
	out, err := exec.Command("git", "config", "--global", key).Output()
	return err == nil && strings.TrimSpace(string(out)) != ""
}
