package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/saireddy-shyamakura/springx/internal/postgen"
	"github.com/saireddy-shyamakura/springx/internal/prompt"
)

func init() {
	postgen.Register(&readmeHook{})
}

type readmeHook struct{}

func (r *readmeHook) Name() string { return "readme" }

func (r *readmeHook) Run(projectPath string, cfg *prompt.ProjectConfig) error {
	path := filepath.Join(projectPath, "README.md")

	// Create a minimal README if Spring Initializr didn't generate one.
	if _, err := os.Stat(path); os.IsNotExist(err) {
		header := fmt.Sprintf("# %s\n\nA Spring Boot application.\n", cfg.ProjectName)
		if err := os.WriteFile(path, []byte(header), 0644); err != nil {
			return err
		}
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}

	// Do not append the section more than once (idempotent).
	if strings.Contains(string(data), "<!-- springx-generated -->") {
		return nil
	}

	deps := "none"
	if len(cfg.Dependencies) > 0 {
		deps = strings.Join(cfg.Dependencies, ", ")
	}

	section := fmt.Sprintf(`

<!-- springx-generated -->
## springx Generation Info

| Field            | Value                         |
|------------------|-------------------------------|
| Template         | %s |
| Java Version     | %s |
| Build Tool       | %s |
| Packaging        | %s |
| Dependencies     | %s |
| Generated At     | %s (UTC) |

> Generated by [springx](https://github.com/saireddy-shyamakura/springx).
<!-- /springx-generated -->
`,
		padCell(cfg.ProjectName),
		padCell(cfg.JavaVersion),
		padCell(cfg.BuildTool),
		padCell(cfg.Packaging),
		padCell(deps),
		padCell(time.Now().UTC().Format("2006-01-02 15:04:05")),
	)

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString(section)
	return err
}

// padCell right-pads s to 29 characters so the markdown table stays aligned.
func padCell(s string) string {
	const width = 29
	if len(s) >= width {
		return s
	}
	return s + strings.Repeat(" ", width-len(s))
}
