// Package aws is an example springx plugin that adds AWS-specific project
// templates, post-generation hooks, and dependency groups.
//
// # How to use this example
//
// Blank-import this package in your main.go (or a dedicated plugins.go file)
// to activate it:
//
//	import _ "github.com/saireddy-shyamakura/springx/plugins/examples/aws"
//
// The plugin registers itself via init(), so no other wiring is needed.
//
// # What this plugin contributes
//
//   - Templates : "aws-lambda", "aws-s3"
//   - Hooks     : "aws-sam"  (generates a SAM template.yaml)
//   - Deps      : "AWS" group with common Spring Cloud AWS starters
package aws

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/saireddy-shyamakura/springx/internal/metadata"
	"github.com/saireddy-shyamakura/springx/internal/plugins"
	"github.com/saireddy-shyamakura/springx/internal/postgen"
	"github.com/saireddy-shyamakura/springx/internal/prompt"
	"github.com/saireddy-shyamakura/springx/internal/templates"
)

func init() {
	plugins.RegisterPlugin(&awsPlugin{})
}

// ── Plugin struct ─────────────────────────────────────────────────────────────

type awsPlugin struct{}

// ── Plugin (core interface) ───────────────────────────────────────────────────

func (p *awsPlugin) Manifest() plugins.Manifest {
	return plugins.Manifest{
		Name:        "aws",
		Version:     "1.0.0",
		Author:      "springx contributors",
		Description: "AWS-specific templates, SAM hook, and Spring Cloud AWS dependency group.",
		Homepage:    "https://github.com/saireddy-shyamakura/springx/tree/main/plugins/examples/aws",
		Tags:        []string{"aws", "lambda", "s3", "cloud", "sam"},
	}
}

// ── TemplatePlugin ────────────────────────────────────────────────────────────

func (p *awsPlugin) Templates() []templates.Template {
	return []templates.Template{
		{
			Name:        "aws-lambda",
			Description: "Spring Boot AWS Lambda function with Spring Cloud Function.",
			Dependencies: []string{
				"web",
				"actuator",
				"validation",
				"lombok",
				// Spring Cloud Function + AWS adapter registered by this plugin.
				"cloud-function",
				"aws-lambda",
			},
			Defaults: templates.TemplateDefaults{
				JavaVersion: "21",
				BuildTool:   "maven-project",
				Packaging:   "jar",
			},
		},
		{
			Name:        "aws-s3",
			Description: "Spring Boot application with Spring Cloud AWS S3 integration.",
			Dependencies: []string{
				"web",
				"actuator",
				"validation",
				"lombok",
				"aws-s3",
			},
			Defaults: templates.TemplateDefaults{
				JavaVersion: "21",
				BuildTool:   "maven-project",
				Packaging:   "jar",
			},
		},
	}
}

// ── HookPlugin ────────────────────────────────────────────────────────────────

func (p *awsPlugin) Hooks() []postgen.Hook {
	return []postgen.Hook{&samHook{}}
}

// samHook generates a minimal AWS SAM template.yaml so the project can be
// deployed with `sam build && sam deploy` immediately after generation.
type samHook struct{}

func (h *samHook) Name() string { return "aws-sam" }

func (h *samHook) Run(projectPath string, cfg *prompt.ProjectConfig) error {
	content := buildSAMTemplate(cfg)
	dest := filepath.Join(projectPath, "template.yaml")
	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		return fmt.Errorf("aws-sam hook: failed to write template.yaml: %w", err)
	}
	return nil
}

func buildSAMTemplate(cfg *prompt.ProjectConfig) string {
	return fmt.Sprintf(`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  %s
  SAM template generated by springx aws plugin.

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java%s
    Architectures:
      - x86_64
    Environment:
      Variables:
        SPRING_PROFILES_ACTIVE: cloud

Resources:
  %sFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
`, cfg.ProjectName, cfg.JavaVersion, toPascalCase(cfg.ArtifactID))
}

// toPascalCase converts a kebab-case string to PascalCase for SAM resource names.
func toPascalCase(s string) string {
	if s == "" {
		return "Application"
	}
	result := make([]byte, 0, len(s))
	capitalise := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '-' || c == '_' {
			capitalise = true
			continue
		}
		if capitalise && c >= 'a' && c <= 'z' {
			c -= 32
		}
		result = append(result, c)
		capitalise = false
	}
	return string(result)
}

// ── DependencyProvider ────────────────────────────────────────────────────────

func (p *awsPlugin) DependencyGroups() []metadata.DependencyGroup {
	return []metadata.DependencyGroup{
		{
			Name: "AWS",
			Values: []metadata.DependencyValue{
				{
					ID:          "aws-s3",
					Name:        "Spring Cloud AWS S3",
					Description: "Spring Cloud AWS integration for Amazon S3 object storage.",
				},
				{
					ID:          "aws-sqs",
					Name:        "Spring Cloud AWS SQS",
					Description: "Spring Cloud AWS integration for Amazon SQS messaging.",
				},
				{
					ID:          "aws-sns",
					Name:        "Spring Cloud AWS SNS",
					Description: "Spring Cloud AWS integration for Amazon SNS notifications.",
				},
				{
					ID:          "aws-secrets-manager",
					Name:        "Spring Cloud AWS Secrets Manager",
					Description: "Loads Spring Boot configuration from AWS Secrets Manager.",
				},
				{
					ID:          "aws-parameter-store",
					Name:        "Spring Cloud AWS Parameter Store",
					Description: "Loads Spring Boot configuration from AWS SSM Parameter Store.",
				},
				{
					ID:          "aws-lambda",
					Name:        "Spring Cloud Function AWS Adapter",
					Description: "Deploy Spring Cloud Function apps on AWS Lambda.",
				},
				{
					ID:          "cloud-function",
					Name:        "Spring Cloud Function",
					Description: "Promotes functions as first-class citizens in Spring Boot.",
				},
			},
		},
	}
}
